vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = "#008fff" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#ffffff" })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = "#8f00ff" })
-- vim.api.nvim_set_hl(0, "Comment", { italic = true })
-- vim.api.nvim_set_hl(0, "String", { italic = true, bold = true })
